" Set runtimepath to nonstandard location under ~/.config/
set runtimepath^=~/.config/vim
"let &packpath=&runtimepath

" Source individual config files
source ~/.config/vim/setup.vim
source ~/.config/vim/statusline.vim
source ~/.config/vim/plugins.vim
" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" Enable plugins and load plugin for the detected file type.
filetype plugin on

" Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype on
" Load an indent file for the detected file type.
filetype indent on
" Turn syntax highlighting on.
syntax on

" Add numbers to each line on the left-hand side.
set number
" Highlight cursor line underneath the cursor horizontally.
set cursorline


" Set shift width to 4 spaces.
set shiftwidth=4
" Set tab width to 4 columns.
set tabstop=4
" Use space characters instead of tabs.
set expandtab

" Ignore capital letters during search.
" but override the ignorecase option if searching for capital letters.
set ignorecase
set smartcase
" Use highlighting when doing a search.
set hlsearch

" Enable auto completion menu after pressing TAB.
set wildmenu
